# See: https://github.com/DavidAnson/markdownlint#rules--aliases

default: true

# Code block style
code-block-style:
  style: fenced

# Fenced code block style
code-fence-style:
  style: backtick

# Don't require output for commands
commands-show-output: false

# Emphasis symbol
emphasis-style:
  style: asterisk

# Heading style
heading-style:
  style: atx

# Horizontal rule style
hr-style:
  style: "---"

# Line length
line-length: false

# HTML elements whitelist
no-inline-html:
  allowed_elements:
    - kbd

# Trailing punctuation whitelist
no-trailing-punctuation:
  punctuation: ".:!?"

# Ordered list style
ol-prefix:
  style: ordered

# Capitalization
proper-names:
  code_blocks: false
  names: []

# Bold text symbol
strong-style:
  style: asterisk

# Unordered list symbol
ul-style:
  style: dash
