# Website
url: https://strappazzon.xyz
baseurl: /

meta:
  title: Alberto Strappazzon
  description: |2-
    I'm a hobbyist developer. This website is mainly about my personal projects.
  keywords: ["strappazzon", "alberto strappazzon", "strappazzon alberto"]
  first: Alberto
  last: Strappazzon
  location: Veneto, Italy
  email:
    user: im

timezone: "Europe/Rome"

# Custom directories
includes_dir: _components
layouts_dir: _templates

# Excluded files, folders
exclude:
  - "**/*.psd"
  - bin
  - node_modules
  - frontmatter.json
  - Gemfile
  - LICENSE*
  - package*.json
  - SUPPORT.md

# Included files, folders
include:
  - .well-known

# Frontmatter
defaults:
  - scope:
      path: pages
      type: pages
    values:
      layout: pages
  - scope:
      path: _blog
      # Collection name
      type: blog
    values:
      layout: blog
      toc: true

# Markdown
markdown: kramdown

# Kramdown
# See: https://kramdown.gettalong.org/options.html
kramdown:
  # Arrow Pointing Downwards Then Curving Leftwards
  footnote_backlink: "&#10550;"
  html_to_native: true
  input: GFM
  # Disable smart quotes
  smart_quotes: "apos,apos,quot,quot"
  syntax_highlighter: rouge
  # See: https://rouge-ruby.github.io/docs/#configuration
  syntax_highlighter_opts: {}

# anchors.rb plugin
anchors:
  prefix: section

# CSS
sass:
  sourcemap: development
  style: compressed

# jekyll-autoprefixer-v2 plugin
autoprefixer:
  browsers:
    - last 2 versions
    - not dead
    - firefox esr
    - chrome 126
  exclude:
    - "**/vendors/*"
  only_production: true

# jekyll-terser plugin
jekyll-terser:
  only_production: true

# jekyll-toc plugin
toc:
  min_level: 2
  max_level: 3
  no_toc_section_class: toc-skip
  list_class: toc-entries

# Blog
collections:
  blog:
    output: true
    permalink: /:collection/:year-:month-:day/:title/

blog_meta:
  title: "Strappazzon's Blog"

# jekyll-paginate-v2 plugin
pagination:
  collection: blog
  enabled: true
  permalink: /:num/
  per_page: 5
  # Explicitly set because
  # https://github.com/sverrirs/jekyll-paginate-v2/issues/230
  sort_reverse: true
  title: :title
autopages:
  # Disabled because
  # https://github.com/sverrirs/jekyll-paginate-v2/issues/176
  # https://github.com/sverrirs/jekyll-paginate-v2/issues/237
  enabled: false
  tags: {}
