# Website
url: https://strappazzon.xyz
baseurl: /
title: Alberto Strappazzon

# Custom directories
includes_dir: _components
layouts_dir: _templates

# Markdown
markdown: kramdown
kramdown:
  # See: https://kramdown.gettalong.org/options.html
  input: GFM
  # Arrow Pointing Downwards Then Curving Leftwards
  footnote_backlink: "&#10550;"
  syntax_highlighter: rouge
  # See: https://rouge-ruby.github.io/docs/#configuration
  syntax_highlighter_opts: {}
  html_to_native: true
  #parse_block_html: true

# anchors.rb plugin
anchors:
  prefix: section

# CSS
sass:
  sourcemap: development
  style: compressed

# jekyll-autoprefixer plugin
autoprefixer:
  browsers:
    - last 2 versions
    - not dead
    - firefox esr
    - chrome 85
  exclude:
    - "**/vendors/*"
  only_production: true

# Excluded files, folders
exclude:
  - "**/*.psd"
  - bin
  - node_modules
  - frontmatter.json
  - Gemfile
  - LICENSE*
  - package*.json
  - SUPPORT.md

# Included files, folders
include:
  - .well-known

# Frontmatter
defaults:
  - scope:
      path: pages
      type: pages
    values:
      layout: pages
  - scope:
      path: _blog
      # Collection name
      type: blog
    values:
      layout: blog

# Blog
title_blog: Strappazzon's Blog

collections:
  blog:
    output: true
    permalink: /:collection/:year-:month-:day/:title/

# jekyll-paginate-v2 plugin
pagination:
  enabled: true
  collection: blog
  per_page: 5
  # Explicitly set because
  #   https://github.com/sverrirs/jekyll-paginate-v2/issues/230
  sort_reverse: true
  permalink: /:num/
  title: :title
autopages:
  # Disabled because
  #   https://github.com/sverrirs/jekyll-paginate-v2/issues/176
  #   https://github.com/sverrirs/jekyll-paginate-v2/issues/237
  enabled: false
  tags: {}

timezone: "Europe/Rome"
