# Website
url: https://strappazzon.xyz
baseurl: /
title: Alberto Strappazzon

# Custom directories
includes_dir: _components
layouts_dir: _templates

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false # May be changed
  html_to_native: true
  #parse_block_html: true

# CSS
sass:
  sourcemap: development
  style: compressed

# CSS Autoprefixer
autoprefixer:
  browsers:
    - last 2 versions
  only_production: true

# Excluded files
exclude:
  - "**/*.psd"
  - bin
  - frontmatter.json
  - Gemfile
  - LICENSE.txt
  - SUPPORT.md

# Included files
include:
  - .well-known

# Blog
title_blog: Strappazzon's Blog

collections:
  blog:
    output: true
    permalink: /:collection/:year-:month-:day/:title/

# Blog pagination
pagination:
  enabled: true
  collection: blog
  per_page: 5
  sort_reverse: true # Explicitly set because https://github.com/sverrirs/jekyll-paginate-v2/issues/230
  permalink: /:num/
  title: :title
autopages:
  # Disabled because
  # https://github.com/sverrirs/jekyll-paginate-v2/issues/176
  # https://github.com/sverrirs/jekyll-paginate-v2/issues/237
  enabled: false
  tags: {}

timezone: "Europe/Rome"
