# Website
url: https://strappazzon.xyz
baseurl: /
title: Alberto Strappazzon

# Custom directories
includes_dir: _components
layouts_dir: _templates

# Ruby gems
plugins:
  - jekyll-autoprefixer
  - jekyll-sitemap

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false # May be changed
  html_to_native: true
  #parse_block_html: true

# CSS
sass:
  style: compressed

# CSS Autoprefixer
autoprefixer:
  browsers:
    - last 2 versions
  only_production: true

# Sitemap
sitemap:
  file: /sitemap.xml

# Excluded files
exclude:
  - frontmatter.json
  - Gemfile
  - LICENSE.txt
  - README.md
  - "**/*.psd"

# Included files
include:
  - .well-known

# Blog
title_blog: Strappazzon's Blog

collections:
  blog:
    output: true
    permalink: /:collection/:year-:month-:day/:title/

timezone: "Europe/Rome"
