# Build
[build]
  command = "jekyll build"
  # Relative path to the repository root
  publish = "_site/"

# Headers
[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Content-Security-Policy = "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self'; font-src 'self'; manifest-src 'self'; frame-ancestors 'none';"
      Access-Control-Allow-Origin = "*"
      Referrer-Policy = "no-referrer"
      Feature-Policy = "autoplay 'self';camera 'none';fullscreen 'self';geolocation 'none';microphone 'none';payment 'none'"
      Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
      Cache-Control = '''
      max-age=0,
      no-cache,
      no-store,
      must-revalidate'''

# Redirect old Keys page
[[redirects]]
  from = "/keys/*"
  to = "/accounts/"
  status = 301

# Redirect projects homepages back to GitHub Pages
[[redirects]]
  from = "/GRW-GHOST-Buster/"
  to = "https://strappazzon.github.io/GRW-GHOST-Buster/"
  status = 301

[[redirects]]
  from = "/Screendere-Beat/"
  to = "https://strappazzon.github.io/Screendere-Beat/"
  status = 301

[[redirects]]
  from = "/PD2-SuperBLT-Hasher/"
  to = "https://strappazzon.github.io/PD2-SuperBLT-Hasher/"
  status = 301

[[redirects]]
  from = "/teleme7ry/"
  to = "https://strappazzon.github.io/teleme7ry/"
  status = 301

[[redirects]]
  from = "/tor-exit-page/"
  to = "https://strappazzon.github.io/tor-exit-page/"
  status = 301

[[redirects]]
  from = "/tor-exit-page/demo/"
  to = "https://strappazzon.github.io/tor-exit-page/demo/"
  status = 301

# 404
# Keep this redirect at the end!
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false
