# Data about myself and the website

first: Alberto
last: Strappazzon
location: Veneto, Italy

title: Alberto Strappazzon
description: |2-
  I'm a hobbyist developer. This website is mainly about my personal projects.

keywords: ["strappazzon", "alberto strappazzon", "strappazzon alberto"]
