name: Build Website (From PR)

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".*/**"
      - ".*"
      - "!.well-known/**"
      - "!.jekyll.yml"
      - "!.tool-versions"
      - "bin/**"
      - "static/psd/**"
      - "frontmatter.json"
      - "LICENSE*"
      - "SUPPORT.md"

jobs:
  main:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5.0.0

      - name: Setup Ruby
        env:
          BUNDLE_SPECIFIC_PLATFORM: 1
        uses: ruby/setup-ruby@v1.257.0
        with:
          bundler-cache: true

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --config .jekyll.yml
