name: Build Website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-app:
    name: "Build Website"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: ruby/setup-ruby@v1.75.0
      with:
        bundler: Gemfile.lock
        bundler-cache: true

    - run: bundle exec jekyll build
