name: Build Website

on:
  push:
    branches: [ master ]
    paths-ignore:
      - ".*/**"
      - ".*"
      - "!.ruby-version"
      - "robots.txt"
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-www:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.75.0

    - name: Run Bundler
      env:
        BUNDLE_SPECIFIC_PLATFORM: 1
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
