name: Build Website (Production)

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".*/**"
      - ".*"
      - "!.cloudflare/**"
      - "!.well-known/**"
      - "!.ruby-version"
      - "bin/**"
      - "frontmatter.json"
      - "LICENSE*"
      - "SUPPORT.md"
  workflow_dispatch:

jobs:
  main:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0

      - name: Setup Ruby
        env:
          BUNDLE_SPECIFIC_PLATFORM: 1
        uses: ruby/setup-ruby@v1.134.0
        with:
          bundler-cache: true

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build
          cp .cloudflare/_headers _site/_headers
          cp .cloudflare/_redirects _site/_redirects

      - name: Production Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: _site
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
          COMMIT_NAME: Alberto Strappazzon
          COMMIT_EMAIL: a@strappazzon.xyz
