name: Build Website (Test)

on:
  push:
    branches:
      - "dev-*"
      - "dev/**"
      - "test-*"
      - "test/**"
    paths-ignore:
      - ".*/**"
      - ".*"
      - "!.routing/**"
      - "!.well-known/**"
      - "!.jekyll.yml"
      - "!.tool-versions"
      - "bin/**"
      - "static/psd/**"
      - "frontmatter.json"
      - "LICENSE*"
      - "SUPPORT.md"

jobs:
  main:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Setup Ruby
        env:
          BUNDLE_SPECIFIC_PLATFORM: 1
        uses: ruby/setup-ruby@v1.224.0
        with:
          bundler-cache: true

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: development
        run: |
          bundle exec jekyll build --config .jekyll.yml
          cp .routing/_headers _site/_headers
          cp .routing/_redirects _site/_redirects

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          # https://github.com/git-lfs/git-lfs/issues/5749
          GIT_CLONE_PROTECTION_ACTIVE: false
          REPO: self
          BRANCH: build-test
          FOLDER: _site
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build Test: ({sha}) {msg}"
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: github-actions[bot]@users.noreply.github.com
