name: Lint Ruby Code

on:
  pull_request:
    branches:
      - master
    paths:
      - "_plugins/**.rb"

jobs:
  rubocop:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0

      - name: Setup Ruby
        env:
          BUNDLE_SPECIFIC_PLATFORM: 1
        uses: ruby/setup-ruby@v1.134.0
        with:
          bundler-cache: true

      - name: Run RuboCop
        uses: reviewdog/action-rubocop@v2.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          use_bundler: true
          workdir: "./_plugins"
          rubocop_version: gemfile
          rubocop_flags: -D -E -S
          reporter: github-pr-review
          fail_on_error: true
